
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package cxf.client.service.cxf.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Fri Jun 24 16:49:05 CST 2016
 * Generated source version: 2.2.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "IHelloServiceService",
                      portName = "HelloWsPort",
                      targetNamespace = "service.cxf.service.client.cxf",
                      wsdlLocation = "http://localhost:8080/ws/sayHelloServiceImpl?wsdl",
                      endpointInterface = "cxf.client.service.cxf.service.HelloWs")
                      
public class HelloWsImpl implements HelloWs {

    private static final Logger LOG = Logger.getLogger(HelloWsImpl.class.getName());

    /* (non-Javadoc)
     * @see cxf.client.service.cxf.service.HelloWs#sayHello(java.lang.String  name )*
     */
    public java.lang.String sayHello(java.lang.String name) { 
        LOG.info("Executing operation sayHello");
        System.out.println(name);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cxf.client.service.cxf.service.HelloWs#download(*
     */
    public cxf.client.service.cxf.service.CxfFileWrapper download() { 
        LOG.info("Executing operation download");
        try {
            cxf.client.service.cxf.service.CxfFileWrapper _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cxf.client.service.cxf.service.HelloWs#upload(cxf.client.service.cxf.service.CxfFileWrapper  file )*
     */
    public boolean upload(cxf.client.service.cxf.service.CxfFileWrapper file) { 
        LOG.info("Executing operation upload");
        System.out.println(file);
        try {
            boolean _return = false;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
