
package cxf.client.service.cxf.service;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.2.3
 * Fri Jun 24 16:49:05 CST 2016
 * Generated source version: 2.2.3
 * 
 */
 
public class HelloWs_HelloWsPort_Server{

    protected HelloWs_HelloWsPort_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new HelloWsImpl();
        String address = "http://localhost:8080/ws/sayHelloServiceImpl";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new HelloWs_HelloWsPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
