package cxf.client.service.cxf.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Fri Jun 24 16:49:05 CST 2016
 * Generated source version: 2.2.3
 * 
 */
 
@WebService(targetNamespace = "service.cxf.service.client.cxf", name = "HelloWs")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWs {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "service.cxf.service.client.cxf", className = "cxf.client.service.cxf.service.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "service.cxf.service.client.cxf", className = "cxf.client.service.cxf.service.SayHelloResponse")
    @WebMethod
    public java.lang.String sayHello(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "download", targetNamespace = "service.cxf.service.client.cxf", className = "cxf.client.service.cxf.service.Download")
    @ResponseWrapper(localName = "downloadResponse", targetNamespace = "service.cxf.service.client.cxf", className = "cxf.client.service.cxf.service.DownloadResponse")
    @WebMethod
    public cxf.client.service.cxf.service.CxfFileWrapper download();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "upload", targetNamespace = "service.cxf.service.client.cxf", className = "cxf.client.service.cxf.service.Upload")
    @ResponseWrapper(localName = "uploadResponse", targetNamespace = "service.cxf.service.client.cxf", className = "cxf.client.service.cxf.service.UploadResponse")
    @WebMethod
    public boolean upload(
        @WebParam(name = "file", targetNamespace = "")
        cxf.client.service.cxf.service.CxfFileWrapper file
    );
}
