
/*
 * 
 */

package cxf.client.service.cxf.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.3
 * Fri Jun 24 16:49:05 CST 2016
 * Generated source version: 2.2.3
 * 
 */


@WebServiceClient(name = "IHelloServiceService", 
                  wsdlLocation = "http://localhost:8080/ws/sayHelloServiceImpl?wsdl",
                  targetNamespace = "service.cxf.service.client.cxf") 
public class IHelloServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("service.cxf.service.client.cxf", "IHelloServiceService");
    public final static QName HelloWsPort = new QName("service.cxf.service.client.cxf", "HelloWsPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ws/sayHelloServiceImpl?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/ws/sayHelloServiceImpl?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public IHelloServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IHelloServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IHelloServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns HelloWs
     */
    @WebEndpoint(name = "HelloWsPort")
    public HelloWs getHelloWsPort() {
        return super.getPort(HelloWsPort, HelloWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWs
     */
    @WebEndpoint(name = "HelloWsPort")
    public HelloWs getHelloWsPort(WebServiceFeature... features) {
        return super.getPort(HelloWsPort, HelloWs.class, features);
    }

}
